services:
  - type: web
    name: kinopoisk-project
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn kinopoisk_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: romankino.onrender.com
    database:
      name: kinopoisk-db
      databaseName: kinopoisk
      user: kinopoisk_user

